# Generated by Django 5.1.6 on 2025-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("I", "In Progress"), ("C", "Completed")],
                default="P",
                max_length=1,
            ),
        ),
    ]
